const PREFIX='chiayi.osteoporosis.v1.';
let memory={},timer;
function read(k){try{return localStorage.getItem(PREFIX+k)??memory[k]??''}catch{return memory[k]||''}}
function save(k,v){memory[k]=v;try{localStorage.setItem(PREFIX+k,v)}catch{say('瀏覽器無法保存；請在離開前匯出紀錄。')}}
function say(t){document.getElementById('toast').textContent=t;clearTimeout(timer);timer=setTimeout(()=>document.getElementById('toast').textContent='',3200)}
async function copyText(t){try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(t);say('已複製，請貼到使用的 AI 工具。')}catch{document.getElementById('manual').value=t;document.getElementById('copyDialog').showModal();document.getElementById('manual').select()}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(b)copyText(COPY[b.dataset.copy])});
document.getElementById('closeDialog').onclick=()=>document.getElementById('copyDialog').close();document.getElementById('selectAll').onclick=()=>{document.getElementById('manual').focus();document.getElementById('manual').select()};
const entries=[...document.querySelectorAll('.exercise')];
const categoryTabs=[...document.querySelectorAll('[data-category-tab]')];
let activeCategory=categoryTabs.length?(read('practice-category')||'起步'):'';
if(categoryTabs.length&&!categoryTabs.some(b=>b.dataset.categoryTab===activeCategory))activeCategory='起步';
categoryTabs.forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.categoryTab;save('practice-category',activeCategory);const q=document.getElementById('search');if(q)q.value='';const u=document.getElementById('unfinished');if(u)u.checked=false;try{history.replaceState(null,'',location.pathname+location.search)}catch{}filter();const first=activeCategory==='使用工具'?document.getElementById('TOOLS-00'):entries.find(a=>!a.hidden);if(first){const bar=document.querySelector('.category-bar');const offset=(bar?bar.getBoundingClientRect().height:0)+16;window.scrollTo({top:Math.max(0,window.scrollY+first.getBoundingClientRect().top-offset),behavior:'instant'})}}));
document.querySelectorAll('[data-save]').forEach(el=>{let v=read(el.dataset.save);if(el.type==='checkbox')el.checked=v==='1';else el.value=v;el.addEventListener('input',()=>{save(el.dataset.save,el.type==='checkbox'?(el.checked?'1':'0'):el.value);const a=el.closest('.exercise');if(a)save('last',location.pathname.split('/').pop()+'#'+a.id);filter()})});
function filter(){const isTools=activeCategory==='使用工具';const panel=document.getElementById('TOOLS-00');if(panel)panel.hidden=!isTools;document.querySelector('.filters')?.toggleAttribute('hidden',isTools);document.getElementById('count')?.toggleAttribute('hidden',isTools);const query=(document.getElementById('search')?.value||'').trim().toLowerCase(),cat=categoryTabs.length?activeCategory:(document.getElementById('category')?.value||''),unfinished=document.getElementById('unfinished')?.checked;categoryTabs.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.categoryTab===activeCategory)));let n=0;entries.forEach(a=>{a.hidden=!(a.textContent.toLowerCase().includes(query)||a.dataset.search.toLowerCase().includes(query))||(cat&&a.dataset.category!==cat)||(unfinished&&a.querySelector('[data-done]')?.checked);if(!a.hidden)n++});const c=document.getElementById('count');if(c)c.textContent=`${categoryTabs.length?(categoryTabs.find(b=>b.dataset.categoryTab===activeCategory)?.textContent+' · '):''}顯示 ${n} / ${entries.filter(a=>!cat||a.dataset.category===cat).length} 題 · 本分類已完成 ${entries.filter(a=>(!cat||a.dataset.category===cat)&&a.querySelector('[data-done]')?.checked).length} 題`;const empty=document.getElementById('empty');if(empty)empty.hidden=isTools||n!==0}
['search','category','unfinished'].forEach(id=>document.getElementById(id)?.addEventListener('input',filter));filter();
function hash(){let id;try{id=decodeURIComponent(location.hash.slice(1))}catch{return}const a=document.getElementById(id);if(!a||!a.classList.contains('exercise'))return;if(categoryTabs.length){activeCategory=a.dataset.category;save('practice-category',activeCategory)}for(const k of ['search','category']){const el=document.getElementById(k);if(el)el.value=''}const u=document.getElementById('unfinished');if(u)u.checked=false;filter();const fold=a.querySelector('.mission-fold');if(fold)fold.open=true;a.scrollIntoView();save('last',location.pathname.split('/').pop()+'#'+id)}
window.addEventListener('hashchange',hash);if(location.hash)requestAnimationFrame(hash);
const mode=document.getElementById('mode');if(mode){mode.value=read('mode')||'guided';const set=()=>{document.body.classList.toggle('challenge',mode.value==='challenge');save('mode',mode.value)};mode.onchange=set;set()}
function records(){const d={...memory};try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k.startsWith(PREFIX))d[k.slice(PREFIX.length)]=localStorage.getItem(k)}}catch{}return d}
document.getElementById('export').onclick=()=>{const data=records(),lines=['嘉義醫院 AI 練習紀錄',new Date().toLocaleString('zh-TW'),''];for(const [k,v]of Object.entries(data))if(v&&v!=='0')lines.push(k+'：'+v);const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='嘉義醫院練習紀錄.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.getElementById('reset').onclick=()=>{if(!confirm('清除練習紀錄？建議先匯出備份。'))return;try{Object.keys(records()).forEach(k=>localStorage.removeItem(PREFIX+k))}catch{}memory={};location.reload()};
const hp=document.getElementById('homeProgress');if(hp){hp.textContent=`已標記完成 ${Object.entries(records()).filter(([k,v])=>k.endsWith('-done')&&v==='1').length} 題。`;const last=read('last');if(/^(practice|missions|materials)\.html#[A-Z]+-\d+$/.test(last)){const a=document.getElementById('resume');a.href=last;a.textContent='繼續上次練習 →'}}
document.getElementById('copyMap')?.addEventListener('click',()=>{let rows=[];for(let i=1;i<=3;i++){const context=read(`map-${i}-context`).trim();if(context)rows.push(`${i}. ${context} → ${read(`map-${i}-card`)||'待選練習'}`)}if(!rows.length)return say('先填寫一個工作情境。');copyText('我的 AI 工作地圖\n'+rows.join('\n'))});
const routeItems=[...document.querySelectorAll('[data-route-id]')];
if(routeItems.length){let done=0;routeItems.forEach(el=>{const complete=read(el.dataset.routeId+'-done')==='1';if(complete)done++;el.querySelector('.route-status').textContent=complete?'已完成':'待練習'});document.getElementById('routeProgress').textContent=`入門路線已完成 ${done} / ${routeItems.length} 題`}

// Mission bodies remain collapsed until selected. Deep links open their target.
document.querySelectorAll('[data-collapse-mission]').forEach(b=>b.addEventListener('click',()=>{const fold=b.closest('.mission-fold');fold.open=false;fold.querySelector('summary').focus();fold.closest('article').scrollIntoView({block:'start'})}));
