"""骨鬆衛教簡報的能力導覽。"""
ROUTE=[('START-01', '體驗白話衛教文字'), ('START-02', '體驗水豚衛教插圖'), ('SEARCH-01', '核對骨鬆來源'), ('WRITE-13A', '規劃六頁衛教大綱'), ('WRITE-13B', '完成逐頁詳細內容'), ('DOC-00', '把來源加入筆記本'), ('DOC-08', '用定稿內容生成簡報'), ('DOC-08A', '自行設定字體與配色'), ('PRO-06', '完成五分鐘試講'), ('START-03', '製作骨鬆互動測驗')]
CAPABILITIES=[('生成', '把需求變成可修改的草稿或畫面。', ['WRITE-03', 'VIS-02', 'PIC-01', 'PRO-02']), ('理解與擷取', '从文字、圖片及語音取得資訊，再核對。', ['DOC-01', 'READ-01', 'VOICE-01']), ('分類與轉換', '把零散資料整理成可用結構。', ['WRITE-07', 'DATA-05', 'VOICE-02']), ('分析與比較', '看差異、找趨勢，區分觀察與推論。', ['DATA-03', 'DATA-10', 'PRO-05']), ('查找與研究', '搜尋來源，比對適用條件與證據。', ['SEARCH-01', 'SEARCH-02']), ('協作與推演', '釐清需求、練習對話並找盲點。', ['WRITE-14', 'ROLE-01', 'ROLE-02']), ('執行與自動化', '建立工具與流程，保留人工確認。', ['TOOL-02', 'TOOL-12', 'FLOW-13', 'FLOW-16'])]
CONTEXT={'起步': ('第一次嘗試 AI，想了解它能協助什麼時', '尚未核對就把第一次輸出當成正確答案', '體驗結果與檢查紀錄'), '文字': ('要把提供的資料整理、改寫或形成草稿時', '缺少來源卻要求補出事實、數字或承諾', '文字草稿，需核對後才能對外使用'), '資料': ('想用理解測驗找出簡報需改善的重點時', '樣本與分母不明卻要求推論療效', '統計與改稿建議，須核對計算及適用範圍'), '視覺': ('需要構圖、插圖或視覺表達的初稿時', '要求生成圖像作為真實事件證據', '圖像草稿，需核對文字、構圖與輸出用途'), '圖片簡報': ('文字已整理好，需要轉成投影片畫面時', '內容仍頻繁變更，卻只保留不可編輯圖片', '圖片與文字稿，需組頁及實際播放驗收'), '專業簡報': ('要將骨鬆知識整理成易懂簡報時', '來源未核對就製作成正式衛教內容', '可編輯或播放的簡報，須經醫療審閱與試講'), 'NotebookLM 專題': ('已有文件來源，需要問答、整理或轉成不同形式時', '來源缺漏卻要求確定答案', '附依據的文件產出，須對原文檢查'), '工具': ('需要衛教問答或簡報輔助功能時', '把小工具當成診斷或治療決策工具', '可操作的工具，須核對答案與實際測試'), '工作流程': ('想將固定工作整理成可重複的步驟時', '把 AI 的口頭確認當成已建立排程或執行成功', '流程設定或草案，實際執行須確認工具狀態'), '衛教簡報': ('要把來源、內容與呈現串成簡報時', '缺乏可靠來源卻要求生成醫療結論', '簡報與核對紀錄，須完成專業審閱'), '搜尋查證': ('需要核對簡報中的醫療主張時', '只憑搜尋摘要就引用醫療資訊', '來源核對表與待確認事項'), '圖片理解': ('要從圖片擷取表格或讀取圖表時', '未核對辨識結果就引用數據', '經人工核對的擷取結果與解讀'), '語音應用': ('想將試講或口述需求整理成文字時', '未取得同意就錄製他人或上傳個資', '轉錄與修訂清單，須回聽核對'), '角色演練': ('想練習衛教簡報後的聽眾問答時', '把模擬回應當成對真實病人的診療', '演練紀錄與說法修訂，仍須專業核對')}

def home(titles):
 from html import escape as h
 def link(id):return f'<a href="practice.html#{id}">{id}｜{h(titles[id])}</a>'
 return '<section class="hero"><h1>讓骨鬆衛教更清楚，讓溝通有依據。</h1><p class="lead">以骨鬆衛教為簡報主題，帶醫療人員練習資料查證、白話講稿、圖像、簡報與互動。練習個案與測驗數據均為虛構。</p><div class="actions"><a class="primary" href="practice.html#START-01">開始第一題</a><a href="#capabilities">查看 AI 應用地圖</a></div></section><section id="beginner"><h2>入門必修・十題路線</h2><p>可分次完成；每題核對成果後再勾選完成。</p><p id="routeProgress" role="status"></p><ol class="learning-route">'+''.join(f'<li data-route-id="{id}">{link(id)}<p>{h(purpose)}</p><span class="route-status"></span></li>' for id,purpose in ROUTE)+'</ol></section><section id="capabilities"><h2>AI 應用地圖</h2><p>從工作動作選能力，同一項工作可以組合多種用法。</p><div class="capability-grid">'+''.join('<section class="capability"><h3>'+name+'</h3><p>'+desc+'</p><div class="catalog">'+''.join(link(id) for id in ids)+'</div></section>' for name,desc,ids in CAPABILITIES)+'</div></section><section><h2>把能力串起來</h2><div class="actions"><a href="missions.html">整合任務</a><a href="materials.html">練習素材</a></div></section><section><h2>我的進度</h2><p id="homeProgress"></p><a id="resume" href="practice.html">繼續練習</a></section>'
